services:
  postgres:
    image: postgres:16-alpine
    container_name: notification-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: notification_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: notification-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:7-alpine
    container_name: notification-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: